apiBaseUrl=http://192.168.0.101:4111
apiVersion=/api/v1
admin.username=admin
admin.password=admin
uiRemote=http://192.168.0.101:4444/wd/hub/
uiBaseUrl=http://frontend
browser=chrome
browserSize=1920x1080

# API Backend Version Control
api.backend.version=with_database_with_fix

# Database configuration
db.url=jdbc:postgresql://192.168.0.101:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver