name: Run Tests

on: [ push, workflow_dispatch ]

jobs:
  run-tests:
    name: Set up services (review apps) and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven repositories
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Services
        run: cd infra/docker_compose && bash restart_docker.sh && cd ../..

      - name: Run Tests
        run: ./mvnw clean test -q
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://localhost:80
          SELENOID_URL: http://localhost:4444
          SELENOID_UI_URL: http://localhost:6567
          DB_URL: jdbc:postgresql://localhost:5433/nbank
          DB_USERNAME: postgres
          DB_PASSWORD: postgres